// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
 * NOTICE: This file was generated by spritesheet_assembler.
 */

UI.Icon.setSpriteSheet({
  size: '69px 81px',
  descriptors: {
    'sprite7': {x: 0, y: 0, width: 40, height: 40},
    'sprite5': {x: -42, y: 0, width: 25, height: 25},
    'sprite6': {x: 0, y: -42, width: 24, height: 15},
    'sprite3': {x: 0, y: -59, width: 20, height: 20},
    'sprite4': {x: -22, y: -59, width: 20, height: 20},
    'sprite2': {x: -26, y: -42, width: 15, height: 15},
    'sprite1': {x: -42, y: -27, width: 10, height: 10},
  }
});