// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
 * NOTICE: This file was generated by spritesheet_assembler.
 */

UI.Icon.setSpriteSheet({
  size: '40px 40px',
  descriptors: {
    'sprite1': {x: 0, y: 0, width: 20, height: 20},
    'sprite2': {x: -20, y: 0, width: 20, height: 20},
    'sprite3': {x: 0, y: -20, width: 20, height: 20},
    'sprite4': {x: -20, y: -20, width: 20, height: 20},
  }
});